# Static country display metadata used for Telegram country buttons.
# No network calls or extra runtime dependency is required.
COUNTRY_META = {
    'AE': ('971', 'United Arab Emirates'),
    'AF': ('93', 'Afghanistan'),
    'AG': ('1268', 'Antigua and Barbuda'),
    'AI': ('1264', 'Anguilla'),
    'AL': ('355', 'Albania'),
    'AM': ('374', 'Armenia'),
    'AO': ('244', 'Angola'),
    'AR': ('54', 'Argentina'),
    'AS': ('1684', 'American Samoa'),
    'AT': ('43', 'Austria'),
    'AU': ('61', 'Australia'),
    'AW': ('297', 'Aruba'),
    'AZ': ('994', 'Azerbaijan'),
    'BA': ('387', 'Bosnia and Herzegovina'),
    'BB': ('1246', 'Barbados'),
    'BD': ('880', 'Bangladesh'),
    'BE': ('32', 'Belgium'),
    'BF': ('226', 'Burkina Faso'),
    'BG': ('359', 'Bulgaria'),
    'BH': ('973', 'Bahrain'),
    'BI': ('257', 'Burundi'),
    'BJ': ('229', 'Benin'),
    'BM': ('1441', 'Bermuda'),
    'BN': ('673', 'Brunei'),
    'BO': ('591', 'Bolivia'),
    'BR': ('55', 'Brazil'),
    'BS': ('1242', 'The Bahamas'),
    'BT': ('975', 'Bhutan'),
    'BW': ('267', 'Botswana'),
    'BY': ('375', 'Belarus'),
    'BZ': ('501', 'Belize'),
    'CA': ('1', 'Canada'),
    'CC': ('61', 'Cocos (Keeling) Islands'),
    'CD': ('243', 'Democratic Republic of the Congo'),
    'CF': ('236', 'Central African Republic'),
    'CG': ('242', 'Republic of the Congo'),
    'CH': ('41', 'Switzerland'),
    'CI': ('225', 'Ivory Coast'),
    'CK': ('682', 'Cook Islands'),
    'CL': ('56', 'Chile'),
    'CM': ('237', 'Cameroon'),
    'CN': ('86', 'China'),
    'CO': ('57', 'Colombia'),
    'CR': ('506', 'Costa Rica'),
    'CU': ('53', 'Cuba'),
    'CV': ('238', 'Cape Verde'),
    'CX': ('61', 'Christmas Island'),
    'CY': ('357', 'Cyprus'),
    'CZ': ('420', 'Czech Republic'),
    'DE': ('49', 'Germany'),
    'DJ': ('253', 'Djibouti'),
    'DK': ('45', 'Denmark'),
    'DM': ('1767', 'Dominica'),
    'DO': ('1809', 'Dominican Republic'),
    'DZ': ('213', 'Algeria'),
    'EC': ('593', 'Ecuador'),
    'EE': ('372', 'Estonia'),
    'EG': ('20', 'Egypt'),
    'EH': ('212', 'Western Sahara'),
    'ER': ('291', 'Eritrea'),
    'ES': ('34', 'Spain'),
    'ET': ('251', 'Ethiopia'),
    'FI': ('358', 'Finland'),
    'FJ': ('679', 'Fiji'),
    'FK': ('500', 'Falkland Islands'),
    'FM': ('691', 'Federated States of Micronesia'),
    'FO': ('298', 'Faroe Islands'),
    'FR': ('33', 'France'),
    'GA': ('241', 'Gabon'),
    'GB': ('44', 'United Kingdom'),
    'GD': ('1473', 'Grenada'),
    'GE': ('995', 'Georgia'),
    'GF': ('594', 'French Guiana'),
    'GG': ('44', 'Guernsey'),
    'GH': ('233', 'Ghana'),
    'GI': ('350', 'Gibraltar'),
    'GL': ('299', 'Greenland'),
    'GM': ('220', 'The Gambia'),
    'GN': ('224', 'Guinea'),
    'GP': ('590', 'Guadeloupe'),
    'GQ': ('240', 'Equatorial Guinea'),
    'GR': ('30', 'Greece'),
    'GS': ('500', 'South Georgia'),
    'GT': ('502', 'Guatemala'),
    'GU': ('1671', 'Guam'),
    'GW': ('245', 'Guinea-Bissau'),
    'GY': ('592', 'Guyana'),
    'HK': ('852', 'Hong Kong'),
    'HM': ('', 'Heard Island and McDonald Islands'),
    'HN': ('504', 'Honduras'),
    'HR': ('385', 'Croatia'),
    'HT': ('509', 'Haiti'),
    'HU': ('36', 'Hungary'),
    'ID': ('62', 'Indonesia'),
    'IE': ('353', 'Ireland'),
    'IL': ('972', 'Israel'),
    'IM': ('44', 'Isle of Man'),
    'IN': ('91', 'India'),
    'IO': ('246', 'British Indian Ocean Territory'),
    'IQ': ('964', 'Iraq'),
    'IR': ('98', 'Iran'),
    'IS': ('354', 'Iceland'),
    'IT': ('39', 'Italy'),
    'JE': ('44', 'Jersey'),
    'JM': ('1876', 'Jamaica'),
    'JO': ('962', 'Jordan'),
    'JP': ('81', 'Japan'),
    'KE': ('254', 'Kenya'),
    'KG': ('996', 'Kyrgyzstan'),
    'KH': ('855', 'Cambodia'),
    'KI': ('686', 'Kiribati'),
    'KM': ('269', 'Comoros'),
    'KN': ('1869', 'Saint Kitts and Nevis'),
    'KP': ('850', 'North Korea'),
    'KR': ('82', 'South Korea'),
    'KW': ('965', 'Kuwait'),
    'KY': ('1345', 'Cayman Islands'),
    'KZ': ('76', 'Kazakhstan'),
    'LA': ('856', 'Laos'),
    'LB': ('961', 'Lebanon'),
    'LC': ('1758', 'Saint Lucia'),
    'LI': ('423', 'Liechtenstein'),
    'LK': ('94', 'Sri Lanka'),
    'LR': ('231', 'Liberia'),
    'LS': ('266', 'Lesotho'),
    'LT': ('370', 'Lithuania'),
    'LU': ('352', 'Luxembourg'),
    'LV': ('371', 'Latvia'),
    'LY': ('218', 'Libya'),
    'MA': ('212', 'Morocco'),
    'MC': ('377', 'Monaco'),
    'MD': ('373', 'Moldova'),
    'MG': ('261', 'Madagascar'),
    'MH': ('692', 'Marshall Islands'),
    'MK': ('389', 'Republic of Macedonia'),
    'ML': ('223', 'Mali'),
    'MN': ('976', 'Mongolia'),
    'MO': ('853', 'Macau'),
    'MP': ('1670', 'Northern Mariana Islands'),
    'MQ': ('596', 'Martinique'),
    'MR': ('222', 'Mauritania'),
    'MS': ('1664', 'Montserrat'),
    'MT': ('356', 'Malta'),
    'MU': ('230', 'Mauritius'),
    'MV': ('960', 'Maldives'),
    'MW': ('265', 'Malawi'),
    'MX': ('52', 'Mexico'),
    'MY': ('60', 'Malaysia'),
    'MZ': ('258', 'Mozambique'),
    'NA': ('264', 'Namibia'),
    'NC': ('687', 'New Caledonia'),
    'NE': ('227', 'Niger'),
    'NF': ('672', 'Norfolk Island'),
    'NG': ('234', 'Nigeria'),
    'NI': ('505', 'Nicaragua'),
    'NL': ('31', 'Netherlands'),
    'NO': ('47', 'Norway'),
    'NP': ('977', 'Nepal'),
    'NR': ('674', 'Nauru'),
    'NU': ('683', 'Niue'),
    'NZ': ('64', 'New Zealand'),
    'OM': ('968', 'Oman'),
    'PA': ('507', 'Panama'),
    'PE': ('51', 'Peru'),
    'PF': ('689', 'French Polynesia'),
    'PG': ('675', 'Papua New Guinea'),
    'PH': ('63', 'Philippines'),
    'PK': ('92', 'Pakistan'),
    'PL': ('48', 'Poland'),
    'PM': ('508', 'Saint Pierre and Miquelon'),
    'PN': ('64', 'Pitcairn Islands'),
    'PR': ('1787', 'Puerto Rico'),
    'PT': ('351', 'Portugal'),
    'PW': ('680', 'Palau'),
    'PY': ('595', 'Paraguay'),
    'QA': ('974', 'Qatar'),
    'RE': ('262', 'Réunion'),
    'RO': ('40', 'Romania'),
    'RS': ('381', 'Serbia'),
    'RU': ('7', 'Russia'),
    'RW': ('250', 'Rwanda'),
    'SA': ('966', 'Saudi Arabia'),
    'SB': ('677', 'Solomon Islands'),
    'SC': ('248', 'Seychelles'),
    'SD': ('249', 'Sudan'),
    'SE': ('46', 'Sweden'),
    'SG': ('65', 'Singapore'),
    'SH': ('290', 'Saint Helena'),
    'SI': ('386', 'Slovenia'),
    'SJ': ('4779', 'Svalbard and Jan Mayen'),
    'SK': ('421', 'Slovakia'),
    'SL': ('232', 'Sierra Leone'),
    'SM': ('378', 'San Marino'),
    'SN': ('221', 'Senegal'),
    'SO': ('252', 'Somalia'),
    'SR': ('597', 'Suriname'),
    'SS': ('211', 'South Sudan'),
    'ST': ('239', 'São Tomé and Príncipe'),
    'SV': ('503', 'El Salvador'),
    'SY': ('963', 'Syria'),
    'SZ': ('268', 'Swaziland'),
    'TD': ('235', 'Chad'),
    'TF': ('', 'French Southern and Antarctic Lands'),
    'TG': ('228', 'Togo'),
    'TH': ('66', 'Thailand'),
    'TJ': ('992', 'Tajikistan'),
    'TK': ('690', 'Tokelau'),
    'TL': ('670', 'East Timor'),
    'TM': ('993', 'Turkmenistan'),
    'TN': ('216', 'Tunisia'),
    'TO': ('676', 'Tonga'),
    'TR': ('90', 'Turkey'),
    'TT': ('1868', 'Trinidad and Tobago'),
    'TV': ('688', 'Tuvalu'),
    'TW': ('886', 'Taiwan'),
    'TZ': ('255', 'Tanzania'),
    'UA': ('380', 'Ukraine'),
    'UG': ('256', 'Uganda'),
    'US': ('1', 'United States'),
    'UY': ('598', 'Uruguay'),
    'UZ': ('998', 'Uzbekistan'),
    'VC': ('1784', 'Saint Vincent and the Grenadines'),
    'VE': ('58', 'Venezuela'),
    'VN': ('84', 'Vietnam'),
    'VU': ('678', 'Vanuatu'),
    'WF': ('681', 'Wallis and Futuna'),
    'WS': ('685', 'Samoa'),
    'YE': ('967', 'Yemen'),
    'YT': ('262', 'Mayotte'),
    'ZA': ('27', 'South Africa'),
    'ZM': ('260', 'Zambia'),
    'ZW': ('263', 'Zimbabwe'),
}

COUNTRY_ALPHA3 = {
    'ARE': 'AE',
    'AFG': 'AF',
    'ATG': 'AG',
    'AIA': 'AI',
    'ALB': 'AL',
    'ARM': 'AM',
    'AGO': 'AO',
    'ARG': 'AR',
    'ASM': 'AS',
    'AUT': 'AT',
    'AUS': 'AU',
    'ABW': 'AW',
    'AZE': 'AZ',
    'BIH': 'BA',
    'BRB': 'BB',
    'BGD': 'BD',
    'BEL': 'BE',
    'BFA': 'BF',
    'BGR': 'BG',
    'BHR': 'BH',
    'BDI': 'BI',
    'BEN': 'BJ',
    'BMU': 'BM',
    'BRN': 'BN',
    'BOL': 'BO',
    'BRA': 'BR',
    'BHS': 'BS',
    'BTN': 'BT',
    'BWA': 'BW',
    'BLR': 'BY',
    'BLZ': 'BZ',
    'CAN': 'CA',
    'CCK': 'CC',
    'COD': 'CD',
    'CAF': 'CF',
    'COG': 'CG',
    'CHE': 'CH',
    'CIV': 'CI',
    'COK': 'CK',
    'CHL': 'CL',
    'CMR': 'CM',
    'CHN': 'CN',
    'COL': 'CO',
    'CRI': 'CR',
    'CUB': 'CU',
    'CPV': 'CV',
    'CXR': 'CX',
    'CYP': 'CY',
    'CZE': 'CZ',
    'DEU': 'DE',
    'DJI': 'DJ',
    'DNK': 'DK',
    'DMA': 'DM',
    'DOM': 'DO',
    'DZA': 'DZ',
    'ECU': 'EC',
    'EST': 'EE',
    'EGY': 'EG',
    'ESH': 'EH',
    'ERI': 'ER',
    'ESP': 'ES',
    'ETH': 'ET',
    'FIN': 'FI',
    'FJI': 'FJ',
    'FLK': 'FK',
    'FSM': 'FM',
    'FRO': 'FO',
    'FRA': 'FR',
    'GAB': 'GA',
    'GBR': 'GB',
    'GRD': 'GD',
    'GEO': 'GE',
    'GUF': 'GF',
    'GGY': 'GG',
    'GHA': 'GH',
    'GIB': 'GI',
    'GRL': 'GL',
    'GMB': 'GM',
    'GIN': 'GN',
    'GLP': 'GP',
    'GNQ': 'GQ',
    'GRC': 'GR',
    'SGS': 'GS',
    'GTM': 'GT',
    'GUM': 'GU',
    'GNB': 'GW',
    'GUY': 'GY',
    'HKG': 'HK',
    'HMD': 'HM',
    'HND': 'HN',
    'HRV': 'HR',
    'HTI': 'HT',
    'HUN': 'HU',
    'IDN': 'ID',
    'IRL': 'IE',
    'ISR': 'IL',
    'IMN': 'IM',
    'IND': 'IN',
    'IOT': 'IO',
    'IRQ': 'IQ',
    'IRN': 'IR',
    'ISL': 'IS',
    'ITA': 'IT',
    'JEY': 'JE',
    'JAM': 'JM',
    'JOR': 'JO',
    'JPN': 'JP',
    'KEN': 'KE',
    'KGZ': 'KG',
    'KHM': 'KH',
    'KIR': 'KI',
    'COM': 'KM',
    'KNA': 'KN',
    'PRK': 'KP',
    'KOR': 'KR',
    'KWT': 'KW',
    'CYM': 'KY',
    'KAZ': 'KZ',
    'LAO': 'LA',
    'LBN': 'LB',
    'LCA': 'LC',
    'LIE': 'LI',
    'LKA': 'LK',
    'LBR': 'LR',
    'LSO': 'LS',
    'LTU': 'LT',
    'LUX': 'LU',
    'LVA': 'LV',
    'LBY': 'LY',
    'MAR': 'MA',
    'MCO': 'MC',
    'MDA': 'MD',
    'MDG': 'MG',
    'MHL': 'MH',
    'MKD': 'MK',
    'MLI': 'ML',
    'MNG': 'MN',
    'MAC': 'MO',
    'MNP': 'MP',
    'MTQ': 'MQ',
    'MRT': 'MR',
    'MSR': 'MS',
    'MLT': 'MT',
    'MUS': 'MU',
    'MDV': 'MV',
    'MWI': 'MW',
    'MEX': 'MX',
    'MYS': 'MY',
    'MOZ': 'MZ',
    'NAM': 'NA',
    'NCL': 'NC',
    'NER': 'NE',
    'NFK': 'NF',
    'NGA': 'NG',
    'NIC': 'NI',
    'NLD': 'NL',
    'NOR': 'NO',
    'NPL': 'NP',
    'NRU': 'NR',
    'NIU': 'NU',
    'NZL': 'NZ',
    'OMN': 'OM',
    'PAN': 'PA',
    'PER': 'PE',
    'PYF': 'PF',
    'PNG': 'PG',
    'PHL': 'PH',
    'PAK': 'PK',
    'POL': 'PL',
    'SPM': 'PM',
    'PCN': 'PN',
    'PRI': 'PR',
    'PRT': 'PT',
    'PLW': 'PW',
    'PRY': 'PY',
    'QAT': 'QA',
    'REU': 'RE',
    'ROU': 'RO',
    'SRB': 'RS',
    'RUS': 'RU',
    'RWA': 'RW',
    'SAU': 'SA',
    'SLB': 'SB',
    'SYC': 'SC',
    'SDN': 'SD',
    'SWE': 'SE',
    'SGP': 'SG',
    'SHN': 'SH',
    'SVN': 'SI',
    'SJM': 'SJ',
    'SVK': 'SK',
    'SLE': 'SL',
    'SMR': 'SM',
    'SEN': 'SN',
    'SOM': 'SO',
    'SUR': 'SR',
    'SSD': 'SS',
    'STP': 'ST',
    'SLV': 'SV',
    'SYR': 'SY',
    'SWZ': 'SZ',
    'TCD': 'TD',
    'ATF': 'TF',
    'TGO': 'TG',
    'THA': 'TH',
    'TJK': 'TJ',
    'TKL': 'TK',
    'TLS': 'TL',
    'TKM': 'TM',
    'TUN': 'TN',
    'TON': 'TO',
    'TUR': 'TR',
    'TTO': 'TT',
    'TUV': 'TV',
    'TWN': 'TW',
    'TZA': 'TZ',
    'UKR': 'UA',
    'UGA': 'UG',
    'USA': 'US',
    'URY': 'UY',
    'UZB': 'UZ',
    'VCT': 'VC',
    'VEN': 'VE',
    'VNM': 'VN',
    'VUT': 'VU',
    'WLF': 'WF',
    'WSM': 'WS',
    'YEM': 'YE',
    'MYT': 'YT',
    'ZAF': 'ZA',
    'ZMB': 'ZM',
    'ZWE': 'ZW',
}

COUNTRY_ALIASES = {
    'abw': 'AW',
    'afg': 'AF',
    'afghanistan': 'AF',
    'ago': 'AO',
    'aia': 'AI',
    'alb': 'AL',
    'albania': 'AL',
    'algeria': 'DZ',
    'american samoa': 'AS',
    'angola': 'AO',
    'anguilla': 'AI',
    'antigua and barbuda': 'AG',
    'are': 'AE',
    'arg': 'AR',
    'argentina': 'AR',
    'arm': 'AM',
    'armenia': 'AM',
    'aruba': 'AW',
    'asm': 'AS',
    'atf': 'TF',
    'atg': 'AG',
    'aus': 'AU',
    'australia': 'AU',
    'austria': 'AT',
    'aut': 'AT',
    'aze': 'AZ',
    'azerbaijan': 'AZ',
    'bahrain': 'BH',
    'bangladesh': 'BD',
    'barbados': 'BB',
    'bdi': 'BI',
    'bel': 'BE',
    'belarus': 'BY',
    'belgium': 'BE',
    'belize': 'BZ',
    'ben': 'BJ',
    'benin': 'BJ',
    'bermuda': 'BM',
    'bfa': 'BF',
    'bgd': 'BD',
    'bgr': 'BG',
    'bhr': 'BH',
    'bhs': 'BS',
    'bhutan': 'BT',
    'bih': 'BA',
    'blr': 'BY',
    'blz': 'BZ',
    'bmu': 'BM',
    'bol': 'BO',
    'bolivia': 'BO',
    'bolivia plurinational state of': 'BO',
    'bosnia and herzegovina': 'BA',
    'botswana': 'BW',
    'bra': 'BR',
    'brazil': 'BR',
    'brb': 'BB',
    'british indian ocean territory': 'IO',
    'brn': 'BN',
    'brunei': 'BN',
    'brunei darussalam': 'BN',
    'btn': 'BT',
    'bulgaria': 'BG',
    'burkina faso': 'BF',
    'burundi': 'BI',
    'bwa': 'BW',
    'cabo verde': 'CV',
    'caf': 'CF',
    'cambodia': 'KH',
    'cameroon': 'CM',
    'can': 'CA',
    'canada': 'CA',
    'cape verde': 'CV',
    'cayman islands': 'KY',
    'cck': 'CC',
    'central african republic': 'CF',
    'chad': 'TD',
    'che': 'CH',
    'chile': 'CL',
    'china': 'CN',
    'chl': 'CL',
    'chn': 'CN',
    'christmas island': 'CX',
    'civ': 'CI',
    'cmr': 'CM',
    'cocos keeling islands': 'CC',
    'cod': 'CD',
    'cog': 'CG',
    'cok': 'CK',
    'col': 'CO',
    'colombia': 'CO',
    'com': 'KM',
    'comoros': 'KM',
    'cook islands': 'CK',
    'costa rica': 'CR',
    'cote d ivoire': 'CI',
    'cpv': 'CV',
    'cri': 'CR',
    'croatia': 'HR',
    'cub': 'CU',
    'cuba': 'CU',
    'cxr': 'CX',
    'cym': 'KY',
    'cyp': 'CY',
    'cyprus': 'CY',
    'cze': 'CZ',
    'czech republic': 'CZ',
    'czechia': 'CZ',
    'côte d ivoire': 'CI',
    'democratic republic of the congo': 'CD',
    'denmark': 'DK',
    'deu': 'DE',
    'dji': 'DJ',
    'djibouti': 'DJ',
    'dma': 'DM',
    'dnk': 'DK',
    'dom': 'DO',
    'dominica': 'DM',
    'dominican republic': 'DO',
    'dza': 'DZ',
    'east timor': 'TL',
    'ecu': 'EC',
    'ecuador': 'EC',
    'egy': 'EG',
    'egypt': 'EG',
    'el salvador': 'SV',
    'equatorial guinea': 'GQ',
    'eri': 'ER',
    'eritrea': 'ER',
    'esh': 'EH',
    'esp': 'ES',
    'est': 'EE',
    'estonia': 'EE',
    'eswatini': 'SZ',
    'eth': 'ET',
    'ethiopia': 'ET',
    'falkland islands': 'FK',
    'faroe islands': 'FO',
    'federated states of micronesia': 'FM',
    'fiji': 'FJ',
    'fin': 'FI',
    'finland': 'FI',
    'fji': 'FJ',
    'flk': 'FK',
    'fra': 'FR',
    'france': 'FR',
    'french guiana': 'GF',
    'french polynesia': 'PF',
    'french southern and antarctic lands': 'TF',
    'fro': 'FO',
    'fsm': 'FM',
    'gab': 'GA',
    'gabon': 'GA',
    'gbr': 'GB',
    'geo': 'GE',
    'georgia': 'GE',
    'germany': 'DE',
    'ggy': 'GG',
    'gha': 'GH',
    'ghana': 'GH',
    'gib': 'GI',
    'gibraltar': 'GI',
    'gin': 'GN',
    'glp': 'GP',
    'gmb': 'GM',
    'gnb': 'GW',
    'gnq': 'GQ',
    'grc': 'GR',
    'grd': 'GD',
    'greece': 'GR',
    'greenland': 'GL',
    'grenada': 'GD',
    'grl': 'GL',
    'gtm': 'GT',
    'guadeloupe': 'GP',
    'guam': 'GU',
    'guatemala': 'GT',
    'guernsey': 'GG',
    'guf': 'GF',
    'guinea': 'GN',
    'guinea bissau': 'GW',
    'gum': 'GU',
    'guy': 'GY',
    'guyana': 'GY',
    'haiti': 'HT',
    'heard island and mcdonald islands': 'HM',
    'hkg': 'HK',
    'hmd': 'HM',
    'hnd': 'HN',
    'honduras': 'HN',
    'hong kong': 'HK',
    'hrv': 'HR',
    'hti': 'HT',
    'hun': 'HU',
    'hungary': 'HU',
    'iceland': 'IS',
    'idn': 'ID',
    'imn': 'IM',
    'ind': 'IN',
    'india': 'IN',
    'indonesia': 'ID',
    'iot': 'IO',
    'iran': 'IR',
    'iran islamic republic of': 'IR',
    'iraq': 'IQ',
    'ireland': 'IE',
    'irl': 'IE',
    'irn': 'IR',
    'irq': 'IQ',
    'isl': 'IS',
    'isle of man': 'IM',
    'isr': 'IL',
    'israel': 'IL',
    'ita': 'IT',
    'italy': 'IT',
    'ivory coast': 'CI',
    'jam': 'JM',
    'jamaica': 'JM',
    'japan': 'JP',
    'jersey': 'JE',
    'jey': 'JE',
    'jor': 'JO',
    'jordan': 'JO',
    'jpn': 'JP',
    'kaz': 'KZ',
    'kazakhstan': 'KZ',
    'ken': 'KE',
    'kenya': 'KE',
    'kgz': 'KG',
    'khm': 'KH',
    'kir': 'KI',
    'kiribati': 'KI',
    'kna': 'KN',
    'kor': 'KR',
    'korea democratic people s republic of': 'KP',
    'korea republic of': 'KR',
    'kuwait': 'KW',
    'kwt': 'KW',
    'kyrgyzstan': 'KG',
    'lao': 'LA',
    'lao people s democratic republic': 'LA',
    'laos': 'LA',
    'latvia': 'LV',
    'lbn': 'LB',
    'lbr': 'LR',
    'lby': 'LY',
    'lca': 'LC',
    'lebanon': 'LB',
    'lesotho': 'LS',
    'liberia': 'LR',
    'libya': 'LY',
    'lie': 'LI',
    'liechtenstein': 'LI',
    'lithuania': 'LT',
    'lka': 'LK',
    'lso': 'LS',
    'ltu': 'LT',
    'lux': 'LU',
    'luxembourg': 'LU',
    'lva': 'LV',
    'mac': 'MO',
    'macau': 'MO',
    'macedonia': 'MK',
    'madagascar': 'MG',
    'malawi': 'MW',
    'malaysia': 'MY',
    'maldives': 'MV',
    'mali': 'ML',
    'malta': 'MT',
    'mar': 'MA',
    'marshall islands': 'MH',
    'martinique': 'MQ',
    'mauritania': 'MR',
    'mauritius': 'MU',
    'mayotte': 'YT',
    'mco': 'MC',
    'mda': 'MD',
    'mdg': 'MG',
    'mdv': 'MV',
    'mex': 'MX',
    'mexico': 'MX',
    'mhl': 'MH',
    'micronesia': 'FM',
    'mkd': 'MK',
    'mli': 'ML',
    'mlt': 'MT',
    'mng': 'MN',
    'mnp': 'MP',
    'moldova': 'MD',
    'monaco': 'MC',
    'mongolia': 'MN',
    'montserrat': 'MS',
    'morocco': 'MA',
    'moz': 'MZ',
    'mozambique': 'MZ',
    'mrt': 'MR',
    'msr': 'MS',
    'mtq': 'MQ',
    'mus': 'MU',
    'mwi': 'MW',
    'mys': 'MY',
    'myt': 'YT',
    'nam': 'NA',
    'namibia': 'NA',
    'nauru': 'NR',
    'ncl': 'NC',
    'nepal': 'NP',
    'ner': 'NE',
    'netherlands': 'NL',
    'new caledonia': 'NC',
    'new zealand': 'NZ',
    'nfk': 'NF',
    'nga': 'NG',
    'nic': 'NI',
    'nicaragua': 'NI',
    'niger': 'NE',
    'nigeria': 'NG',
    'niu': 'NU',
    'niue': 'NU',
    'nld': 'NL',
    'nor': 'NO',
    'norfolk island': 'NF',
    'north korea': 'KP',
    'north macedonia': 'MK',
    'northern mariana islands': 'MP',
    'norway': 'NO',
    'npl': 'NP',
    'nru': 'NR',
    'nzl': 'NZ',
    'oman': 'OM',
    'omn': 'OM',
    'pak': 'PK',
    'pakistan': 'PK',
    'palau': 'PW',
    'pan': 'PA',
    'panama': 'PA',
    'papua new guinea': 'PG',
    'paraguay': 'PY',
    'pcn': 'PN',
    'per': 'PE',
    'peru': 'PE',
    'philippines': 'PH',
    'phl': 'PH',
    'pitcairn islands': 'PN',
    'plw': 'PW',
    'png': 'PG',
    'pol': 'PL',
    'poland': 'PL',
    'portugal': 'PT',
    'pri': 'PR',
    'prk': 'KP',
    'prt': 'PT',
    'pry': 'PY',
    'puerto rico': 'PR',
    'pyf': 'PF',
    'qat': 'QA',
    'qatar': 'QA',
    'republic of korea': 'KR',
    'republic of macedonia': 'MK',
    'republic of moldova': 'MD',
    'republic of the congo': 'CG',
    'reu': 'RE',
    'romania': 'RO',
    'rou': 'RO',
    'rus': 'RU',
    'russia': 'RU',
    'russian federation': 'RU',
    'rwa': 'RW',
    'rwanda': 'RW',
    'réunion': 'RE',
    'saint helena': 'SH',
    'saint kitts and nevis': 'KN',
    'saint lucia': 'LC',
    'saint pierre and miquelon': 'PM',
    'saint vincent and the grenadines': 'VC',
    'samoa': 'WS',
    'san marino': 'SM',
    'sau': 'SA',
    'saudi arabia': 'SA',
    'sdn': 'SD',
    'sen': 'SN',
    'senegal': 'SN',
    'serbia': 'RS',
    'seychelles': 'SC',
    'sgp': 'SG',
    'sgs': 'GS',
    'shn': 'SH',
    'sierra leone': 'SL',
    'singapore': 'SG',
    'sjm': 'SJ',
    'slb': 'SB',
    'sle': 'SL',
    'slovakia': 'SK',
    'slovenia': 'SI',
    'slv': 'SV',
    'smr': 'SM',
    'solomon islands': 'SB',
    'som': 'SO',
    'somalia': 'SO',
    'south africa': 'ZA',
    'south georgia': 'GS',
    'south korea': 'KR',
    'south sudan': 'SS',
    'spain': 'ES',
    'spm': 'PM',
    'srb': 'RS',
    'sri lanka': 'LK',
    'ssd': 'SS',
    'stp': 'ST',
    'sudan': 'SD',
    'sur': 'SR',
    'suriname': 'SR',
    'svalbard and jan mayen': 'SJ',
    'svk': 'SK',
    'svn': 'SI',
    'swaziland': 'SZ',
    'swe': 'SE',
    'sweden': 'SE',
    'switzerland': 'CH',
    'swz': 'SZ',
    'syc': 'SC',
    'syr': 'SY',
    'syria': 'SY',
    'syrian arab republic': 'SY',
    'são tomé and príncipe': 'ST',
    'taiwan': 'TW',
    'tajikistan': 'TJ',
    'tanzania': 'TZ',
    'tcd': 'TD',
    'tgo': 'TG',
    'tha': 'TH',
    'thailand': 'TH',
    'the bahamas': 'BS',
    'the gambia': 'GM',
    'tjk': 'TJ',
    'tkl': 'TK',
    'tkm': 'TM',
    'tls': 'TL',
    'togo': 'TG',
    'tokelau': 'TK',
    'ton': 'TO',
    'tonga': 'TO',
    'trinidad and tobago': 'TT',
    'tto': 'TT',
    'tun': 'TN',
    'tunisia': 'TN',
    'tur': 'TR',
    'turkey': 'TR',
    'turkiye': 'TR',
    'turkmenistan': 'TM',
    'tuv': 'TV',
    'tuvalu': 'TV',
    'twn': 'TW',
    'tza': 'TZ',
    'türkiye': 'TR',
    'u s a ': 'US',
    'uae': 'AE',
    'uga': 'UG',
    'uganda': 'UG',
    'uk': 'GB',
    'ukr': 'UA',
    'ukraine': 'UA',
    'united arab emirates': 'AE',
    'united kingdom': 'GB',
    'united kingdom of great britain and northern ireland': 'GB',
    'united republic of tanzania': 'TZ',
    'united states': 'US',
    'united states of america': 'US',
    'uruguay': 'UY',
    'ury': 'UY',
    'usa': 'US',
    'uzb': 'UZ',
    'uzbekistan': 'UZ',
    'vanuatu': 'VU',
    'vct': 'VC',
    'ven': 'VE',
    'venezuela': 'VE',
    'venezuela bolivarian republic of': 'VE',
    'viet nam': 'VN',
    'vietnam': 'VN',
    'vnm': 'VN',
    'vut': 'VU',
    'wallis and futuna': 'WF',
    'western sahara': 'EH',
    'wlf': 'WF',
    'wsm': 'WS',
    'yem': 'YE',
    'yemen': 'YE',
    'zaf': 'ZA',
    'zambia': 'ZM',
    'zimbabwe': 'ZW',
    'zmb': 'ZM',
    'zwe': 'ZW',
}

def _norm(value: str) -> str:
    import re
    value = value.strip().lower().replace('’', "'")
    value = re.sub(r"[\'.,()\-]", ' ', value)
    return re.sub(r'\s+', ' ', value)

def _flag(iso2: str) -> str:
    return ''.join(chr(ord(ch) + 127397) for ch in iso2.upper())

# Reverse dial-code map (only unique dial codes to avoid wrong guesses)
_DIAL_TO_ISO = {}
for _iso, (_dial, _name) in COUNTRY_META.items():
    if not _dial:
        continue
    if _dial not in _DIAL_TO_ISO:
        _DIAL_TO_ISO[_dial] = _iso
    else:
        # Ambiguous dial code (shared by multiple countries) — do not auto-map
        _DIAL_TO_ISO[_dial] = None

def format_country(country_code: str, country_name: str) -> str:
    """Return a nice label for Telegram buttons: Name + flag + dial if possible."""
    code = str(country_code or "").strip()
    name = str(country_name or "").strip()
    if not name or name == code:
        name = code

    iso2 = ""
    # 1) Direct ISO2
    if len(code) == 2 and code.isalpha() and code.upper() in COUNTRY_META:
        iso2 = code.upper()
    # 2) ISO3
    if not iso2 and len(code) == 3 and code.isalpha():
        iso2 = COUNTRY_ALPHA3.get(code.upper(), "")
    # 3) Name aliases
    key = _norm(name)
    if not iso2:
        iso2 = COUNTRY_ALIASES.get(key, "")
    if not iso2 and key.upper() in COUNTRY_META:
        iso2 = key.upper()
    # 4) Numeric / dial code (only if unique)
    if not iso2 and code.isdigit():
        mapped = _DIAL_TO_ISO.get(code)
        if mapped:
            iso2 = mapped
            # Prefer proper country name from our table
            name = COUNTRY_META[iso2][1]

    if iso2 and iso2 in COUNTRY_META:
        dial = COUNTRY_META[iso2][0]
        nice_name = COUNTRY_META[iso2][1]
        # Prefer our clean name if provider name looks like a number
        if name.isdigit() or not name:
            name = nice_name
        return f"{name} • {_flag(iso2)}{iso2}+{dial}"

    # Fallback: still show something readable instead of bare number
    if code.isdigit():
        return f"Country {code}"
    return name or code
